"""Export data + a small forecasting model for the HTML/CSS/JS website (web/).

    python scripts/export_web_data.py

Writes web/data/config.js, cached.js, demo.js  (plain JS files that set window.AW_*),
so the website works with VS Code Live Server AND by double-clicking index.html.

What the website gets
- zones.................. pilot locations (lat/lon/population assumption)
- model.................. Linear Regression coefficients per horizon (6/12/24 h), so the browser
                          can forecast by itself from live data (no Python server needed)
- cached / demo history.. last 72 hourly rows per zone (+ the Python Random Forest forecast,
                          shown for comparison)
Re-run this script after you fetch real data and retrain.
"""
import json, sys
from datetime import datetime
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src.aqi_calculator import add_aqi_columns                        # noqa: E402
from src.data_cleaner import clean                                     # noqa: E402
from src.data_loader import LOCATIONS, load_cached, load_demo, load_historical  # noqa: E402
from src.feature_engineering import FEATURES, HORIZONS, build_features        # noqa: E402
from src.predictor import _metrics, _time_split, forecast_location, load_bundle  # noqa: E402

OUT = ROOT / "web" / "data"
OUT.mkdir(parents=True, exist_ok=True)
REAL = (ROOT / "data" / ".real_data").exists()
RAW = ["pm25", "pm10", "no2", "so2", "co", "o3", "temp", "humidity", "wind", "wind_dir"]


def write_js(name, var, obj):
    (OUT / name).write_text(f"// Auto-generated by scripts/export_web_data.py - do not edit by hand\nwindow.{var} = "
                            + json.dumps(obj, separators=(",", ":")) + ";\n")


# ---------- 1) linear model for the browser ----------
df = build_features(add_aqi_columns(clean(load_historical())), with_targets=True)
model = {"features": FEATURES, "horizons": {}, "metrics": {}}
for h in HORIZONS:
    t = f"target_{h}h"
    d = df.dropna(subset=FEATURES + [t])
    tr, va, te = _time_split(d)
    lr = LinearRegression().fit(tr[FEATURES], tr[t])
    model["horizons"][h] = {"coef": [float(c) for c in lr.coef_], "intercept": float(lr.intercept_),
                            "rmse": float(_metrics(va[t], lr.predict(va[FEATURES]))["RMSE"])}
    model["metrics"][h] = {"linear_test": _metrics(te[t], lr.predict(te[FEATURES])),
                           "persistence_test": _metrics(te[t], te["aqi"])}
    print(f"{h}h  test MAE  linear {model['metrics'][h]['linear_test']['MAE']:.1f}"
          f"  vs persistence {model['metrics'][h]['persistence_test']['MAE']:.1f}")

zones = {n: {"lat": m["lat"], "lon": m["lon"], "pop": m["pop"]} for n, m in LOCATIONS.items()}
config = {"zones": zones, "model": model, "dataSource": "real" if REAL else "synthetic",
          "generatedAt": datetime.now().isoformat(timespec="minutes")}
write_js("config.js", "AW_CONFIG", config)


# ---------- 2) history + python forecasts ----------
bundle = load_bundle()


def pack(frame):
    frame = add_aqi_columns(clean(frame))
    hist, py = {}, {}
    for name, g in frame.groupby("location"):
        g = g.sort_values("time").tail(72)
        rows = []
        for _, r in g.iterrows():
            row = {"t": r["time"].strftime("%Y-%m-%dT%H:%M")}
            for k in RAW:
                v = r.get(k)
                row[k] = None if pd.isna(v) else round(float(v), 2)
            rows.append(row)
        hist[name] = rows
        f = forecast_location(g, bundle)
        py[name] = {"model": f["model"], **{str(h): f["horizons"][h]["aqi"] for h in HORIZONS}}
    return {"history": hist, "pyForecast": py}


cached = pack(load_cached())
cached["savedAt"] = datetime.now().isoformat(timespec="minutes")
write_js("cached.js", "AW_CACHED", cached)

demo_raw = pd.read_csv(ROOT / "data" / "demo_scenarios.csv", parse_dates=["time"])
demo = {k: pack(load_demo(k)) for k in demo_raw["scenario"].unique()}
write_js("demo.js", "AW_DEMO", demo)
print("Wrote web/data/config.js, cached.js, demo.js  (data source:", config["dataSource"] + ")")
